version: "3"

services:
  api:
    image: tripleparity/docks-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - '8080:8080'
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - type: volume
        source: docks_data
        target: /var/lib/postgresql/data

  docks-ui:
    image: tripleparity/docks-ui:latest
    ports:
      - '4200:80'
    environment:
      - DOCKS_API_ADDRESS=http://127.0.0.1:8080

  demo_nginx:
    image: nginx
    ports:
      - '9000:80'

  demo_wordpress_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  demo_wordpress:
    image: wordpress:latest
    ports:
      - "9001:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: demo_wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
  docks_data:
