version: "3"
services:

  docks:
    image: tripleparity/docks:docker-hub
    container_name: docks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  docks-ui:
    image: tripleparity/docks-ui:docker-hub
    container_name: docks-ui
    ports:
      - 4200:80
