version: "3"

services:
  api:
    image: tripleparity/docks-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    deploy:
      placement:
        constraints: [node.role == manager]

  docks-ui:
    image: tripleparity/docks-ui:latest
    ports:
      - 4200:80
    environment:
      - DOCKS_API_ADDRESS=http://127.0.0.1:8080

